### ISSUE TITLE
condition is not used in the model error.

### ISSUE THREAD

**Issue by xXAvoraXx** [openfga/vscode-ext#249]
I am doing modular model development and I need to add conditions but when I use the word condition I get the following error.

![image](https://github.com/openfga/vscode-ext/assets/6988989/dbf8cd48-dd2f-47a1-a7e3-2e90fd21d3bf)

**Comment by xXAvoraXx** [comment]
@rhamzeh

**Comment by aaguiarz** [comment]
@xXAvoraXx 

Conditions need to be defined in the module where they are being used for now.

**Comment by xXAvoraXx** [comment]
> @xXAvoraXx
> 
> Conditions need to be defined in the module where they are being used for now.

I tested it again and it gives the same error when I define a 'condition'.

> `non_expired_grant` condition is not used in the model.

**Comment by aaguiarz** [comment]
Are you using the condition in the model? Can you paste the full module?

**Comment by xXAvoraXx** [comment]
> Are you using the condition in the model? Can you paste the full module?

In schema: '1.2' the 'conditions' don't work but if I make schema: '1.1' the 'condition' works but this time the 'module' doesn't work. In short, In short, it doesn't matter what the authorization scheme is.

```
module core

type user

type group
  relations
    define assignee: [parent_group, member_group]
    define blocked: [user, role#direct_access, parent_group#direct_access, member_group#direct_access]

    define direct_access: (assignee or direct_access from assignee) but not blocked
    define indirect_access: indirect_access from assignee but not blocked
    define can_access: indirect_access

type parent_group
  relations
    define parent: [parent_group, role]
    define sibling: [parent_group, role]
    define blocked: [user, role#direct_access, parent_group#direct_access] # Grubun Kaynaklara erisiminin ebeveynlere aktarilmasinin kisitlanmasi.

    define direct_access: ((parent or sibling) or (direct_access from parent or direct_access from sibling)) but not blocked
    define indirect_access: (indirect_access from parent or indirect_access from sibling) but not blocked
    define can_access: indirect_access

type member_group
  relations
    define member: [member_group, role]
    define blocked: [user, role#direct_access, member_group#direct_access] # Grubun Kaynaklara erisiminin cocuklara aktarilmasinin kisitlanmasi.

    define direct_access: (member or direct_access from member) but not blocked
    define indirect_access: indirect_access from member but not blocked
    define can_access: indirect_access

type role
  relations
    define parent: [role, parent_group]
    define sibling: [role, parent_group]
    define member: [user]
    define blocked: [user, role#direct_access, parent_group#direct_access]

    define direct_access: (member or parent or sibling) but not blocked
    define indirect_access: (direct_access or (indirect_access from parent or indirect_access from sibling)) but not blocked
    define can_access: indirect_access


condition non_expired_grant(current_time: timestamp, grant_time: timestamp, grant_duration: duration) {
  current_time < grant_time + grant_duration
}
```

**Comment by rhamzeh** [comment]
@xXAvoraXx is there another file using this condition? It does not seem to be used in this file

**Comment by xXAvoraXx** [comment]
> @xXAvoraXx is there another file using this condition? It does not seem to be used in this file

It doesn't matter if it is used, VS-Code gives this error when I make the definition, I just need to write the word 'condition'.

![image](https://github.com/openfga/vscode-ext/assets/6988989/7e27e0d6-37ae-4612-8c32-e0133bb311e0)

**Comment by xXAvoraXx** [comment]
> @xXAvoraXx is there another file using this condition? It does not seem to be used in this file

It was giving an error because I didn't use the function, it's all my fault, I apologize. I was stuck on why it gave an error when I defined 'condition', I didn't think it gave an error because I didn't use it.
