### ISSUE TITLE
SyntaxError on basic model – syntax parsing seems to be broken for 'model'

### ISSUE THREAD

**Issue by rakeshrm** [openfga/vscode-ext#297]
With the latest release `v0.2.23`, getting a syntax error on the first line with `model` – this seems to be broken. This was working in the `v0.2.22` release.

<img width="849" alt="image" src="https://github.com/user-attachments/assets/2c96412e-dc89-4801-b3c9-896a97e77101">

<img width="596" alt="image" src="https://github.com/user-attachments/assets/fb4d9fba-2c7d-4871-b70e-ad9f80fd9510">

**Comment by rhamzeh** [comment]
Thanks for the heads up @rakeshrm - we're releasing v0.2.24 shortly with a fix

**Comment by ewanharris** [comment]
Apologies for the issue here @rakeshrm, v0.2.24 has just been published and VS Code should auto-update soon.

**Comment by rakeshrm** [comment]
Thanks for a lighting fast response and fix @ewanharris @rhamzeh
