### ISSUE TITLE
Allow the extension to be installed on VS Code for the Web

### ISSUE THREAD

**Issue by rhamzeh** [openfga/vscode-ext#56]
https://code.visualstudio.com/docs/editor/vscode-web#_extensions

<img width="1590" alt="Screenshot 2023-08-10 at 3 28 55 PM" src="https://github.com/openfga/vscode-ext/assets/536147/450cca17-8ab8-4e71-8c70-38f4e2345a71">

**Comment by d-jeffery** [comment]
https://code.visualstudio.com/api/extension-guides/web-extensions

**Comment by aaguiarz** [comment]
@rhamzeh @d-jeffery how difficult is this one? It blocks using it from the Github VS Code editor

**Comment by d-jeffery** [comment]
There is a pretty straightforward walkthrough here on how to update and enable existing extensions:
https://code.visualstudio.com/api/extension-guides/web-extensions#update-existing-extensions-to-web-extensions

We need to;
- refactor the package
- provide new entry points
- migrate the existing code to a the entry points
- and add bundling using webpack.

Not minimizing the work involved, but I dont think its too difficult of a problem given what I've read. Testing and time are probably the bigger factors.
