### ISSUE TITLE
Failure when uploading the vsix to the release

### ISSUE THREAD

**Issue by rhamzeh** [openfga/vscode-ext#92]
<img width="1177" alt="Screenshot 2023-10-23 at 12 56 47 PM" src="https://github.com/openfga/vscode-ext/assets/536147/03171a5b-a208-454b-bad0-352b99e8481d">

See: https://github.com/openfga/vscode-ext/actions/runs/6616393757/job/17970798250

**Comment by Siddhant-K-code** [comment]
This has already resolved in latest version of https://github.com/openfga/vscode-ext/blob/main/.github/workflows/publish.yaml
